version: 2.1
executors:
  node-executor:
    docker:
      - image: cimg/node:19.8.1
  python-executor:
    docker:
      - image: cimg/python:3.9.10

jobs:
  build_frontend:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install frontend dependencies
          command: |
            cd frontend
            npm install
      - run:
          name: Run frontend tests
          command: |
            cd frontend
            npm test
      - store_test_results:
          path: test-results.xml
  build_backend:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install backend dependencies
          command: |
            cd backend/django_project-pro/website
            pip install -r ../requirements.txt
      - run:
          name: Run backend tests
          command: |
            cd backend/django_project-pro/website
            python manage.py test
      - store_test_results:
          path: test-results.xml

workflows:
  version: 2
  build-and-test:
    jobs:
      - build_frontend
      - build_backend
