version: 2
jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd frontend
            npm install
      - run:
          name: Run tests
          command: |
            cd frontend
            npm test
      - store_test_results:
          path: test-results.xml
workflows:
  version: 2
  build-and-test:
    jobs:
      - build