version: 2
jobs:
  build:
    docker:
      - image: cimg/node:19.8.1
      - image: cimg/python:3.9.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd frontend
            npm install
            cd ../backend/django_project-pro/website
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            cd frontend
            npm test
            cd ../backend/django_project-pro/website
            python -m unittest discover -s tests -p '*_test.py'
      - store_test_results:
          path: test-results.xml
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
